spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/micro_school_db
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
server:
  port: 8080